### ISSUE TITLE
The progress bar on the Running Sync Dashboard with Child Sites modal could use some spacing

### ISSUE THREAD

**Issue by maxwelljordanwhite** [mainwp/mainwp#120]
**Describe the bug**
Hi! Loving MainWP. This issue is purely cosmetic, but I think it'd lift the interface: The progress bar on the Running Sync Dashboard with Child Sites modal could use left and right spacing to align with the sites below it.

**To Reproduce**
1. Go to your MainWP dashboard
2. Click on 'Sync Dashboard with Child Sites'
3. See error

**Expected behavior**
The loading bar doesn't have any space on the left and right

**Screenshots**
![example line as a guide, on screenshot](https://cdn-std.droplr.net/files/acc_887730/Y9SydJ)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox (64-bit)
 - Version 74.0

**Smartphone (please complete the following information):**
NA

**Additional context**
Also appears to be happening on Chrome 80+

**Comment by bogdan-mainwp** [comment]
Hi @maxwelljordanwhite, thanks for reaching out and sending us your suggestion. 

This actually is not a bug, it's by design and we prefer to keep it this way.

Have you checked the [MainWP Custom Dashboard Extension](https://mainwp.com/extension/mainwp-custom-dashboard-extension/)? It's a free extension that will allow you to make custom CSS changes to your MainWP Dashboard and customize it to your needs. 

Also, if you prefer, you can join the [MainWP Community](https://meta.mainwp.com) and submit your suggestion to the [Features section](https://meta.mainwp.com/c/feature/16) so other users can vote up the request.

Thanks again and kind regards.

**Comment by maxwelljordanwhite** [comment]
Hey @bogdan-mainwp, thanks for the reply! Out of curiosity, why is that preferred? I'll hit up the MainWP Community for this sort of thing going forward. Thanks again!
