### ISSUE TITLE
MainWP - Slow after Update

### ISSUE THREAD

**Issue by Surgical17** [mainwp/mainwp#642]
**Describe the bug**
After updating to 4.5.1.3 the MainWP dashboard became incredible slow to the point of being unusable.
MainWP is hosted in a Wordpress docker on a Server with 32GB of Ram (77% free), SSD, 0.22 CPU load (No CPU intense Apps on the server)
The issue is also not on the WordPress Dashboard as this functions 100% fine. Only after opening MainWP dashboard and clicking on "Sites" it becomes incredibly slow loading up to 5 min.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22
 - Browser Chrome
 - Version 4.5.1.3

**Additional context**
 I also only have 5 Managed Websites and no Automations( Schedules)

**Comment by kwcjr** [comment]
Thank you for reaching out to us about the issue that you are having. 

Would you mind opening a private [Help Desk ticket](https://mainwp.com/my-account/get-support/) so we can collect some additional information & investigate further?

And please refer to this Github thread by its URL in the ticket.

**Comment by kwcjr** [comment]
@riccardodicurti This thread is over 4 months old & we have had 4 releases since then. Can you please make sure that your MainWP Suite is up to date with version 5.0+ & as stated above open a private [Help Desk ticket](https://mainwp.com/my-account/get-support/) so that we can investigate your issue further. 

Thank you for your understanding.
