### ISSUE TITLE
Update Count shows incorrect number

### ISSUE THREAD

**Issue by phalancs** [mainwp/mainwp#67]
After quite some usage time the main plugins/ themes update count on the dashboard shows an incorrect nurmber. I dont know if it is caused by unfinished updates or a bug and how it is calculated but its wrong by the hundreds und not just a sum of the zeros below.

**Comment by bogdan-mainwp** [comment]
Can you please verify that you are using the latest versions of the MainWP plugins (3.4.3)?

**Comment by phalancs** [comment]
Thanks for your update. I have found the issue: I disabled the translations update count, so maybe it is not a real bug but unexpected behaviorand a little irritating nonetheless :)

**Comment by bogdan-mainwp** [comment]
phalancs thanks for the update. This has been assigned to the dev team and it will be sorted out.

**Comment by bogdan-mainwp** [comment]
Scheduled for the next release.

**Comment by bogdan-mainwp** [comment]
Hi @phalancs, I believe that this problem was solved in one of the earlier versions. 

After reporting this problem, we released a whole new major point update that should solve this. If the problem still persists for you, please feel free to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/).

Thanks
