### ISSUE TITLE
MainWP wrongly reports listing issue

### ISSUE THREAD

**Issue by Zodiac1978** [mainwp/mainwp#703]
My newly added site is showing this hardening opportunity:
> /wp-content/, /wp-content/plugins/, /wp-content/themes/ and /wp-content/uploads/ directories listing has not been prevented
> After fixing this issue, an empty index.php will be inserted in these directories to prevent listing. 

Although WordPress is having empty index.php files at these locations for (more than) a decade now:
https://github.com/WordPress/WordPress/tree/master/wp-content
https://github.com/WordPress/WordPress/tree/master/wp-content/plugins
https://github.com/WordPress/WordPress/tree/master/wp-content/themes

**Comment by bogdan-mainwp** [comment]
Hi @Zodiac1978,
Thanks for your patience.
WP by default includes empty index.php file in wp-content, wp-content/plugins and wp-content/themse directories. However, since the wp-content/uploads directory does not come included by default, MainWP probably reports the hardening opportunity due to missing index.php file in the uploads directory. 

Can you please check this and if I am mistaken, please feel free to reach via [helpdesk ticket](https://mainwp.com/my-account/get-support/) so we can check what is going on.

Thanks

**Comment by Zodiac1978** [comment]
You are correct! Adding an empty index.php to the uploads folder is fixing it and WP does not include one in this folder by default.

Although this would not be necessary if the folder is not accessible due to an `Options -Indexes` in a `.htaccess` for example. So wouldn't it be better to try reading the _folder_ instead of trying to read an _index.php_ ?

In my case the folder wouldn't be accessible so this is still a false positive warning.
